---
title: Lab 8 self-assessment
author: Abby Komiske
doc: pdf
---

<!--
2024-04-29: Nice job, Abby. You've got a good handle on the concepts and methods of exploratory data analysis. I look forward to seeing if you apply this knowlege in your prospectus.
 -->

## Assessment

Lab 8 was all about the goal of exploration and its methodology. Exploratory data analysis is meant to discover patterns, describe emerging relationships in corpora, and speculate hypotheses. This process is best for when literature is very scarce, there are major gaps in knowledge, and unchartered territory. In class, we used corpora from British and American Literature of the mid-19th century to explore the data and address the research question, “How has language of the SOTU changed over time?”. The methods included frequency and distributional analysis.

I did not have any major troubles as I followed along with this lab, but rather learned a great deal about exploratory goals. I learned a lot about 'explore' as a goal for quantitative data analysis. Lastly, I only consulted the professor during this process.

